# Generated by Django 4.2.6 on 2024-12-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0002_surveyresponse_questionresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('republished', 'Republished')], default='draft', max_length=12),
        ),
    ]
